### ISSUE TITLE
Ask for help:)

### ISSUE THREAD

**Issue by luojiandan** [granite-cs/PowerBiVisibility#1]
Hi,David,thanks for your script.
my pbi desktop version:
![pbi version](https://user-images.githubusercontent.com/5663556/77439364-e8630100-6e21-11ea-998f-38197d08e291.png)

the two *.pbix file change info:
![change info](https://user-images.githubusercontent.com/5663556/77439168-acc83700-6e21-11ea-9758-dea234759d6f.png)

but,I didn't get this change in JSON file.

can u help me?
thanks:)

[ps demo.zip](https://github.com/granite-cs/PowerBiVisibility/files/4375898/ps.demo.zip)

**Comment by granite-cs** [comment]
I was surprised to find 2 databases in the file PBI.pbix 
When I look at the JSON, it appear that there are 2 internal databases. I am not sure how this happens. I am still learning about PowerBI. Do you see 2 also? One database is the same between files, the other shows the difference.

![image](https://user-images.githubusercontent.com/7861617/77450845-16f4c380-6db1-11ea-956d-e6aedbf3df13.png)

**Comment by granite-cs** [comment]
Ok, I made a mistake because I had both files open at the same time. This script is intended to run with only one PBIX file open at a time.  When I ran each file separately, I saw the difference in the measure expression.
![image](https://user-images.githubusercontent.com/7861617/77452632-663bf380-6db3-11ea-9fac-0e83e55a429e.png)

**Comment by luojiandan** [comment]
sorry for replay so late :(
I think I make a mistake too.
run script before open the right pbi file,right?
I open a blank pbi file before run script,maybe it's my fault,I will try late.

**Comment by luojiandan** [comment]
Hi,David,I open only one file,and run script,but I got an error:
![issue](https://user-images.githubusercontent.com/5663556/77652622-7ddccd00-6fa9-11ea-8c0b-2f6179dbfad4.png)

windows process:
![issue2](https://user-images.githubusercontent.com/5663556/77652712-a5cc3080-6fa9-11ea-9cb2-37893c267cc5.png)

something wrong?

**Comment by luojiandan** [comment]
install sql server? which version?

**Comment by luojiandan** [comment]
@granite-cs 
Hi,David,I install SQL Server 2017，and run script again,I didn't get right json file.
can you help me?send me your exported json file.

this my json file,not have measures.
[JSON Files.zip](https://github.com/granite-cs/PowerBiVisibility/files/4398275/JSON.Files.zip)

**Comment by granite-cs** [comment]
@luojiandan The type of error that you are receiving is strange. I would expect that type of error if the Microsoft.AnalysisServices.Tabular assembly was missing from your computer. But I also expect that it would exist as part of the .NET framework which is on all computers. It also would have expected it to be confirmed if you installed SQL server. 

Question: Are you using a Windows computer? (which Operating System) and is it up to date?

Your version of PowerBI is a little newer then mine. I don't think it will matter, but I will try updating anyhow and see what happens.

Please use powershell to run the command below. It will load the assembly that is missing, and hopefully show us what is wrong on your computer

`[System.Reflection.Assembly]::LoadWithPartialName("Microsoft.AnalysisServices.Tabular")`

![image](https://user-images.githubusercontent.com/7861617/77961350-8aee0a80-728e-11ea-9b62-5a41254142dd.png)

**Comment by luojiandan** [comment]
@granite-cs I'm using Windows 10 Operating System,I run the command in powershell,get the same message.
![DLLTabularConfirmed](https://user-images.githubusercontent.com/5663556/78024588-32e8fe00-738b-11ea-84e7-9dfd35b9f65e.png)

**Comment by luojiandan** [comment]
@granite-cs Hi,David,I get the right json file after I run the command.I didn't do nothing before got your replay,it's magic.
do you mean,the Microsoft.AnalysisServices.Tabular in .net framework?I don't need to install SQL Server 2017?

**Comment by granite-cs** [comment]
@luojiandan I am very glad that it is working. I don't know why it would not work at first. It sounds like a permissions problem. Anyhow, I am glad. Also, I do not believe that you need to install SQL Server for the Powershell script to work. However, the Powershell script can be used to generate SQL code. This is my preferred way to use the script. So you might find SQL Server useful anyhow. But it is not a dependency.

**Comment by luojiandan** [comment]
Hi,David,thank u very much,best wish for u:)
